/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AdoboGrid {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface AdoboGridAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AdoboGrid': Components.AdoboGrid;
  }

  interface StencilIntrinsicElements {
    'adobo-grid': Components.AdoboGridAttributes;
  }


  interface HTMLAdoboGridElement extends Components.AdoboGrid, HTMLStencilElement {}
  var HTMLAdoboGridElement: {
    prototype: HTMLAdoboGridElement;
    new (): HTMLAdoboGridElement;
  };

  interface HTMLElementTagNameMap {
    'adobo-grid': HTMLAdoboGridElement
  }

  interface ElementTagNameMap {
    'adobo-grid': HTMLAdoboGridElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
